name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  TARGET_DIRECTORY: ${{ secrets.TARGET_DIRECTORY }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21]

    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@master
        with:
          version: pnpm@9.12.3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Cache pnpm and Next.js build cache
        uses: actions/cache@main
        with:
          path: |
            ~/.pnpm-store
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Build with Next.js
        run: pnpm next build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quranaz-next-build
          path: ./.next
          include-hidden-files: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: quranaz-next-build
          path: ./.next

      - name: Upload to Ubuntu server
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          source: ./*
          target: ${{ env.TARGET_DIRECTORY }}

      - name: Execute deployment commands on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.TARGET_DIRECTORY }}
            git fetch
            git checkout main
            git pull
            pnpm install
            pm2 restart quran.az
            echo "Files uploaded successfully!"
