name: Run tests and linter

on: [push, pull_request]

env:
  NEXT_PUBLIC_DEFAULT_TRANSLATOR: ${{ vars.NEXT_PUBLIC_DEFAULT_TRANSLATOR }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      
      - uses: pnpm/action-setup@master
        with:
          version: 9.12.3

      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: '21'
          cache: 'pnpm'

      - name: Cache pnpm modules
        uses: actions/cache@main
        with:
          path: |
            ~/.pnpm-store
            !**/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Run tests
        run: pnpm test
